import numpy as np


class Names:
    _names = ["Earl",
              "Annmarie",
              "Edmundo",
              "Kerri",
              "Kaitlin",
              "Tasha",
              "Alonzo",
              "Sondra",
              "Lowell",
              "Carter",
              "Wiley",
              "Daniel",
              "Emile",
              "Trevor",
              "Jeanine",
              "Araceli",
              "Sandy",
              "Janie",
              "Arline",
              "Candice",
              "Tricia",
              "Wilbur",
              "Tim",
              "Diann",
              "Royal",
              "Art",
              "Mary",
              "Marcie",
              "Efrain",
              "Korey",
              "Quentin",
              "Rocco",
              "Ervin",
              "Evelyn",
              "Jackie",
              "Dianna",
              "Frances",
              "Carlos",
              "Clinton",
              "Everett",
              "Lesa",
              "Julio",
              "Gretchen",
              "Zachery",
              "Rosendo",
              "Ronald",
              "Terrance",
              "Cecile",
              "Patti",
              "Jeromy",
              "Rosalie",
              "Roy",
              "Carmela",
              "Reva",
              "Lilly",
              "Carrol",
              "Miles",
              "Fidel",
              "Valentine",
              "Carey",
              "Rebecca",
              "Carmen",
              "Michal",
              "Sam",
              "Sebastian",
              "Cyrus",
              "Blake",
              "Coy",
              "Candace",
              "Louis",
              "Paris",
              "Cristopher",
              "Ann",
              "Fredric",
              "Annette",
              "Pasquale",
              "Julia",
              "Vince",
              "Daisy",
              "Lilia",
              "Debora",
              "Josie",
              "Hazel",
              "Houston",
              "Carol",
              "Mari",
              "Sharron",
              "Vilma",
              "Denis",
              "Roslyn",
              "Courtney",
              "Benjamin",
              "Dewitt",
              "Tyler",
              "Porter",
              "Ollie",
              "Willa"]

    _names_length = len(_names)

    @staticmethod
    def random_name() -> str:
        return Names._names[np.random.randint(Names._names_length, size=1)[0]]
